/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projek.mpf;

import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Tashya
 */
public class masterAdmin extends javax.swing.JFrame {
    
    
    
    /**
     * Creates new form masterAdmin
     */
    public masterAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        itemBMW = new javax.swing.JPanel();
        imgBMW = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        priceLbl = new javax.swing.JLabel();
        stockLbl = new javax.swing.JLabel();
        descLbl = new javax.swing.JLabel();
        viewBMW = new javax.swing.JButton();
        updBMW = new javax.swing.JButton();
        nameBMW = new javax.swing.JTextField();
        priceBMW = new javax.swing.JSpinner();
        stockBMW = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        descTxt = new javax.swing.JTextArea();
        itemDuc = new javax.swing.JPanel();
        imgDuc = new javax.swing.JLabel();
        nameLbl3 = new javax.swing.JLabel();
        priceLbl3 = new javax.swing.JLabel();
        stockLbl3 = new javax.swing.JLabel();
        descLbl3 = new javax.swing.JLabel();
        viewKawa = new javax.swing.JButton();
        updKawa = new javax.swing.JButton();
        nameKawa = new javax.swing.JTextField();
        priceKawa = new javax.swing.JSpinner();
        stockKawa = new javax.swing.JSpinner();
        jScrollPane4 = new javax.swing.JScrollPane();
        descKawa = new javax.swing.JTextArea();
        itemDuc1 = new javax.swing.JPanel();
        imgDuc1 = new javax.swing.JLabel();
        nameLbl4 = new javax.swing.JLabel();
        priceLbl4 = new javax.swing.JLabel();
        stockLbl4 = new javax.swing.JLabel();
        descLbl4 = new javax.swing.JLabel();
        viewDuc = new javax.swing.JButton();
        updDuc = new javax.swing.JButton();
        nameDuc = new javax.swing.JTextField();
        priceDuc = new javax.swing.JSpinner();
        stockDuc = new javax.swing.JSpinner();
        jScrollPane5 = new javax.swing.JScrollPane();
        descDuc = new javax.swing.JTextArea();
        itemDuc2 = new javax.swing.JPanel();
        imgDuc2 = new javax.swing.JLabel();
        nameLbl5 = new javax.swing.JLabel();
        priceLbl5 = new javax.swing.JLabel();
        stockLbl5 = new javax.swing.JLabel();
        descLbl5 = new javax.swing.JLabel();
        viewYmh = new javax.swing.JButton();
        updYmh = new javax.swing.JButton();
        nameYmh = new javax.swing.JTextField();
        priceYmh = new javax.swing.JSpinner();
        stockYmh = new javax.swing.JSpinner();
        jScrollPane6 = new javax.swing.JScrollPane();
        descYmh = new javax.swing.JTextArea();
        botPanel = new javax.swing.JPanel();
        logOutBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Welcome, Admin");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(322, 322, 322))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        imgBMW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projek/mpf/asset/BMW S1000RR (100).png"))); // NOI18N

        nameLbl.setText("Item Name:");

        priceLbl.setText("Price:");

        stockLbl.setText("Stock:");

        descLbl.setText("Description:");

        viewBMW.setText("View Image");
        viewBMW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBMWActionPerformed(evt);
            }
        });

        updBMW.setText("Update Item");
        updBMW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updBMWActionPerformed(evt);
            }
        });

        nameBMW.setText("BMW S1000rr");

        priceBMW.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(714000000L), Long.valueOf(100000000L), Long.valueOf(1000000000L), Long.valueOf(1000000L)));
        priceBMW.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                priceBMWPropertyChange(evt);
            }
        });

        stockBMW.setModel(new javax.swing.SpinnerNumberModel(10, 0, 20, 1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        descTxt.setColumns(20);
        descTxt.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        descTxt.setRows(5);
        descTxt.setText("BMW S1000RR is a sport bike initially made by BMW Motorrad to compete \nin the 2009 Superbike World Championship.");
        jScrollPane1.setViewportView(descTxt);

        javax.swing.GroupLayout itemBMWLayout = new javax.swing.GroupLayout(itemBMW);
        itemBMW.setLayout(itemBMWLayout);
        itemBMWLayout.setHorizontalGroup(
            itemBMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemBMWLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(imgBMW, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(itemBMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemBMWLayout.createSequentialGroup()
                        .addComponent(nameLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameBMW, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(priceBMW, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stockLbl)
                        .addGap(18, 18, 18)
                        .addComponent(stockBMW, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemBMWLayout.createSequentialGroup()
                        .addGroup(itemBMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemBMWLayout.createSequentialGroup()
                                .addComponent(viewBMW)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updBMW))
                            .addGroup(itemBMWLayout.createSequentialGroup()
                                .addComponent(descLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3)))
                .addGap(23, 23, 23))
        );
        itemBMWLayout.setVerticalGroup(
            itemBMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemBMWLayout.createSequentialGroup()
                .addGroup(itemBMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemBMWLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(itemBMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLbl)
                            .addComponent(priceLbl)
                            .addComponent(stockLbl)
                            .addComponent(nameBMW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceBMW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stockBMW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(itemBMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(itemBMWLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(descLbl))
                            .addGroup(itemBMWLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(itemBMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(viewBMW)
                            .addComponent(updBMW)))
                    .addGroup(itemBMWLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imgBMW, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        imgDuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projek/mpf/asset/Kawasaki Ninja H2R (100).png"))); // NOI18N

        nameLbl3.setText("Item Name:");

        priceLbl3.setText("Price:");

        stockLbl3.setText("Stock:");

        descLbl3.setText("Description:");

        viewKawa.setText("View Image");
        viewKawa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewKawaActionPerformed(evt);
            }
        });

        updKawa.setText("Update Item");
        updKawa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updKawaActionPerformed(evt);
            }
        });

        nameKawa.setText("Kawasaki H2R");

        priceKawa.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(978000000L), Long.valueOf(100000000L), Long.valueOf(1000000000L), Long.valueOf(1000000L)));
        priceKawa.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                priceKawaPropertyChange(evt);
            }
        });

        stockKawa.setModel(new javax.swing.SpinnerNumberModel(8, 0, 20, 1));

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setToolTipText("");
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        descKawa.setColumns(20);
        descKawa.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        descKawa.setRows(5);
        descKawa.setText("Kawasaki Ninja H2R is a supercharged supersport class motorcycle in the \nNinja sportbike series.");
        jScrollPane4.setViewportView(descKawa);

        javax.swing.GroupLayout itemDucLayout = new javax.swing.GroupLayout(itemDuc);
        itemDuc.setLayout(itemDucLayout);
        itemDucLayout.setHorizontalGroup(
            itemDucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemDucLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(imgDuc, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(itemDucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemDucLayout.createSequentialGroup()
                        .addComponent(nameLbl3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameKawa, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceLbl3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(priceKawa, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stockLbl3)
                        .addGap(18, 18, 18)
                        .addComponent(stockKawa, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemDucLayout.createSequentialGroup()
                        .addGroup(itemDucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(itemDucLayout.createSequentialGroup()
                                .addComponent(viewKawa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updKawa))
                            .addGroup(itemDucLayout.createSequentialGroup()
                                .addComponent(descLbl3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3)))
                .addGap(23, 23, 23))
        );
        itemDucLayout.setVerticalGroup(
            itemDucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemDucLayout.createSequentialGroup()
                .addGroup(itemDucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemDucLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(itemDucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLbl3)
                            .addComponent(priceLbl3)
                            .addComponent(stockLbl3)
                            .addComponent(nameKawa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceKawa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stockKawa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(itemDucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(itemDucLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(descLbl3))
                            .addGroup(itemDucLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(itemDucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updKawa)
                            .addComponent(viewKawa)))
                    .addGroup(itemDucLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imgDuc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        imgDuc1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projek/mpf/asset/Ducati Panigale (100).png"))); // NOI18N

        nameLbl4.setText("Item Name:");

        priceLbl4.setText("Price:");

        stockLbl4.setText("Stock:");

        descLbl4.setText("Description:");

        viewDuc.setText("View Image");
        viewDuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDucActionPerformed(evt);
            }
        });

        updDuc.setText("Update Item");
        updDuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updDucActionPerformed(evt);
            }
        });

        nameDuc.setText("Ducati Panigale");

        priceDuc.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(812000000L), Long.valueOf(100000000L), Long.valueOf(1000000000L), Long.valueOf(1000000L)));
        priceDuc.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                priceDucPropertyChange(evt);
            }
        });

        stockDuc.setModel(new javax.swing.SpinnerNumberModel(1, 0, 20, 1));

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setToolTipText("");
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        descDuc.setColumns(20);
        descDuc.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        descDuc.setRows(5);
        descDuc.setText("Panigale V4 boosts performance even further and takes track riding to the \nnext level for amateurs and pros alike.");
        jScrollPane5.setViewportView(descDuc);

        javax.swing.GroupLayout itemDuc1Layout = new javax.swing.GroupLayout(itemDuc1);
        itemDuc1.setLayout(itemDuc1Layout);
        itemDuc1Layout.setHorizontalGroup(
            itemDuc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemDuc1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(imgDuc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(itemDuc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemDuc1Layout.createSequentialGroup()
                        .addComponent(nameLbl4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameDuc, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceLbl4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(priceDuc, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stockLbl4)
                        .addGap(18, 18, 18)
                        .addComponent(stockDuc, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemDuc1Layout.createSequentialGroup()
                        .addGroup(itemDuc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(itemDuc1Layout.createSequentialGroup()
                                .addComponent(viewDuc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updDuc))
                            .addGroup(itemDuc1Layout.createSequentialGroup()
                                .addComponent(descLbl4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3)))
                .addGap(26, 26, 26))
        );
        itemDuc1Layout.setVerticalGroup(
            itemDuc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemDuc1Layout.createSequentialGroup()
                .addGroup(itemDuc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemDuc1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(itemDuc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLbl4)
                            .addComponent(priceLbl4)
                            .addComponent(stockLbl4)
                            .addComponent(nameDuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceDuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stockDuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(itemDuc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(itemDuc1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(descLbl4))
                            .addGroup(itemDuc1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(itemDuc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updDuc)
                            .addComponent(viewDuc)))
                    .addGroup(itemDuc1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imgDuc1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        imgDuc2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projek/mpf/asset/Yamaha R1 (100).png"))); // NOI18N

        nameLbl5.setText("Item Name:");

        priceLbl5.setText("Price:");

        stockLbl5.setText("Stock:");

        descLbl5.setText("Description:");

        viewYmh.setText("View Image");
        viewYmh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewYmhActionPerformed(evt);
            }
        });

        updYmh.setText("Update Item");
        updYmh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updYmhActionPerformed(evt);
            }
        });

        nameYmh.setText("Yamaha R1");

        priceYmh.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(689000000L), Long.valueOf(100000000L), Long.valueOf(1000000000L), Long.valueOf(1000000L)));
        priceYmh.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                priceYmhPropertyChange(evt);
            }
        });

        stockYmh.setModel(new javax.swing.SpinnerNumberModel(14, 0, 20, 1));

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setToolTipText("");
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        descYmh.setColumns(20);
        descYmh.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        descYmh.setRows(5);
        descYmh.setText("The R1 is underpinned by a diamond design aluminum frame and comes \nwith an inline-four, 998cc petrol engine.");
        jScrollPane6.setViewportView(descYmh);

        javax.swing.GroupLayout itemDuc2Layout = new javax.swing.GroupLayout(itemDuc2);
        itemDuc2.setLayout(itemDuc2Layout);
        itemDuc2Layout.setHorizontalGroup(
            itemDuc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemDuc2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(imgDuc2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(itemDuc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemDuc2Layout.createSequentialGroup()
                        .addComponent(nameLbl5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameYmh, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceLbl5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(priceYmh, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stockLbl5)
                        .addGap(18, 18, 18)
                        .addComponent(stockYmh, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemDuc2Layout.createSequentialGroup()
                        .addGroup(itemDuc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(itemDuc2Layout.createSequentialGroup()
                                .addComponent(viewYmh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updYmh))
                            .addGroup(itemDuc2Layout.createSequentialGroup()
                                .addComponent(descLbl5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3)))
                .addGap(23, 23, 23))
        );
        itemDuc2Layout.setVerticalGroup(
            itemDuc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemDuc2Layout.createSequentialGroup()
                .addGroup(itemDuc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl5)
                    .addComponent(priceLbl5)
                    .addComponent(stockLbl5)
                    .addComponent(nameYmh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceYmh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockYmh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(itemDuc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemDuc2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(descLbl5))
                    .addGroup(itemDuc2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(itemDuc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updYmh)
                    .addComponent(viewYmh))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(itemDuc2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgDuc2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        logOutBtn.setText("Log Out");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout botPanelLayout = new javax.swing.GroupLayout(botPanel);
        botPanel.setLayout(botPanelLayout);
        botPanelLayout.setHorizontalGroup(
            botPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(botPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitBtn)
                    .addComponent(logOutBtn))
                .addGap(29, 29, 29))
        );
        botPanelLayout.setVerticalGroup(
            botPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botPanelLayout.createSequentialGroup()
                .addComponent(logOutBtn)
                .addGap(18, 18, 18)
                .addComponent(exitBtn))
        );

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(itemBMW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(itemDuc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(itemDuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(itemDuc2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addComponent(itemBMW, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(itemDuc1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(itemDuc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemDuc2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(centerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void viewBMWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBMWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewBMWActionPerformed

    private void updBMWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updBMWActionPerformed
        String name = nameBMW.getText().toString();
        Long price = (Long)priceBMW.getValue();
        Integer stock = (Integer)stockBMW.getValue();
        String desc = descTxt.getText().toString();
        
        if(name.equals("")){
            JOptionPane.showMessageDialog(this, "Item's name must be filled", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(desc.equals("")){
            JOptionPane.showMessageDialog(this, "Item's description must be filled", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updBMWActionPerformed

    private void priceBMWPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_priceBMWPropertyChange
        
    }//GEN-LAST:event_priceBMWPropertyChange

    private void viewKawaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewKawaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewKawaActionPerformed

    private void updKawaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updKawaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updKawaActionPerformed

    private void priceKawaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_priceKawaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_priceKawaPropertyChange

    private void viewDucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewDucActionPerformed

    private void updDucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updDucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updDucActionPerformed

    private void priceDucPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_priceDucPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_priceDucPropertyChange

    private void viewYmhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewYmhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewYmhActionPerformed

    private void updYmhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updYmhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updYmhActionPerformed

    private void priceYmhPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_priceYmhPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_priceYmhPropertyChange

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        login lf = new login();
        lf.setVisible(true);
        lf.pack();
        lf.setLocationRelativeTo(null);
        lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(masterAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(masterAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(masterAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(masterAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new masterAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JTextArea descDuc;
    private javax.swing.JTextArea descKawa;
    private javax.swing.JLabel descLbl;
    private javax.swing.JLabel descLbl3;
    private javax.swing.JLabel descLbl4;
    private javax.swing.JLabel descLbl5;
    private javax.swing.JTextArea descTxt;
    private javax.swing.JTextArea descYmh;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel imgBMW;
    private javax.swing.JLabel imgDuc;
    private javax.swing.JLabel imgDuc1;
    private javax.swing.JLabel imgDuc2;
    private javax.swing.JPanel itemBMW;
    private javax.swing.JPanel itemDuc;
    private javax.swing.JPanel itemDuc1;
    private javax.swing.JPanel itemDuc2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JTextField nameBMW;
    private javax.swing.JTextField nameDuc;
    private javax.swing.JTextField nameKawa;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel nameLbl3;
    private javax.swing.JLabel nameLbl4;
    private javax.swing.JLabel nameLbl5;
    private javax.swing.JTextField nameYmh;
    private javax.swing.JSpinner priceBMW;
    private javax.swing.JSpinner priceDuc;
    private javax.swing.JSpinner priceKawa;
    private javax.swing.JLabel priceLbl;
    private javax.swing.JLabel priceLbl3;
    private javax.swing.JLabel priceLbl4;
    private javax.swing.JLabel priceLbl5;
    private javax.swing.JSpinner priceYmh;
    private javax.swing.JSpinner stockBMW;
    private javax.swing.JSpinner stockDuc;
    private javax.swing.JSpinner stockKawa;
    private javax.swing.JLabel stockLbl;
    private javax.swing.JLabel stockLbl3;
    private javax.swing.JLabel stockLbl4;
    private javax.swing.JLabel stockLbl5;
    private javax.swing.JSpinner stockYmh;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton updBMW;
    private javax.swing.JButton updDuc;
    private javax.swing.JButton updKawa;
    private javax.swing.JButton updYmh;
    private javax.swing.JButton viewBMW;
    private javax.swing.JButton viewDuc;
    private javax.swing.JButton viewKawa;
    private javax.swing.JButton viewYmh;
    // End of variables declaration//GEN-END:variables
}
